version: "3.8"

services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - adonis_app
    volumes:
      - ./frontend:/frontend

  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: ./backend
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 
    depends_on:
      - db    
    env_file:
      - .env
    volumes:
      - ./backend:/home/node/app
    command: dumb-init node --inspect=0.0.0.0 ace serve --watch

  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    container_name: todo_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_db
