version: "3.8"

services:
  frontend:
    #  especifica a pasta contendo um arquivo Dockerfile a partir do qual o Compose vai executar o comando docker build automaticamente.
    build: frontend/
    # container reinicia sempre
    restart: always
    # mapeamento de portas
    ports:
      - 3000:3000
    # o front depende do back
    depends_on:
      - adonis_app
    volumes:
      - ./frontend:/frontend

  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: ./backend
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./backend:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node --inspect=0.0.0.0 ace serve --watch

  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    container_name: todo_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_db
