export default {
	'space-inset-primitives': {
		'spacing-instet-xxs': '2px',
		'spacing-instet-xs': '4px',
		'spacing-instet-s': '8px',
		'spacing-instet-m': '16px',
		'spacing-instet-xm': '24',
		'spacing-instet-xxm': '32px',
		'spacing-instet-l': '48px',
	},
	'space-squish-primitives': {
		'space-squish-xxs': '2px 4px',
		'space-squish-xs': '4px 8px',
		'space-squish-s': '8px 16px',
		'space-squish-m': '16px 32px',
		'space-squish-l': '24px 48px',
	},
	'space-stack-primitives': {
		'space-stack-xxs': '4px',
		'space-stack-xs': '8px',
		'space-stack-s': '12px',
		'space-stack-m': '16px',
		'space-stack-xm': '24px',
		'space-stack-xxm': '32px',
		'space-stack-l': '48px',
		'space-stack-xl': '64px',
	},
	'space-primitives': {
		'spacing-4-xs': '2px',
		'spacing-3-xs': '4px',
		'spacing-2-xs': '8px',
		'spacing-xs': '12px',
		'spacing-s': '16px',
		'spacing-m': '24px',
		'spacing-l': '32px',
		'spacing-xl': '40px',
		'spacing-2-xl': '48px',
		'spacing-3-xl': '56px',
		'spacing-layout-l': '64px',
		'spacing-layout-xl': '96px',
		'spacing-layout-2-xl': '128px',
	},
	'space-inline-primitives': {
		'space-inline-xxs': '4px',
		'space-inline-xs': '8px',
		'space-inline-s': '12px',
		'space-inline-m': '16px',
		'space-inline-xm': '24px',
		'space-inline-xxm': '32px',
		'space-inline-l': '48px',
		'space-inline-xl': '64px',
	},
} as const;
